
# DB connecting properties
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devtest
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true